### ISSUE TITLE
外接显示器的问题

### ISSUE THREAD

**Issue by Daohuai0913** [Ac1d-0-0/MSI-GS65-9SE-hackintosh#1]
老哥你好我想问下你买的扩展坞是 什么转什么的 我买了一根typec转dp的线 接上去却没有反应

**Comment by Ac1dNe9n** [comment]
我用的da300转的hdmi

**Comment by Daohuai0913** [comment]
好的知道了 谢谢老哥

**Comment by Ac1d-0-0** [comment]
还有就是把board-id换成有dp或者hdmi接口的mac版本，新版只有c口

**Comment by Ac1dNe9n** [comment]
还有就是把board-id换成有dp或者hdmi接口的mac版本，新版只有c口，刚把最新版clover的push了，随航问题也解决了，usbport建议自己定制一下。

**Comment by Daohuai0913** [comment]
这个board-id不是很懂 我淘宝看了下 好像都有hdmi 和dp接口把 老哥不升级下嘛 现在都是open core了 感觉比clover好用点

**Comment by Ac1dNe9n** [comment]
我是走扩展坞hdmi dp都可以，内建的无解，禁用了独显。 苹果不会有11代u了黑果也就终结了，就不oc了。

**Comment by Daohuai0913** [comment]
好的 感谢老哥 愚钝的我终于看懂了
