### ISSUE TITLE
雷电接口可以正常驱动吗？

### ISSUE THREAD

**Issue by konstant2016** [Ac1d-0-0/MSI-GS65-9SE-hackintosh#2]
比较看重外接显示器，请问下，Mac下雷电口可以外接显示器吗？

另外：请问下，苹果升级11代处理器和转OC有什么关联吗？

**Comment by Ac1dNe9n** [comment]
雷雳暂时没驱动，现在仅仅是个typec口 ，但是外接显示器没问题了，不过得把board-id设置为有hdmi的机型

**Comment by Ac1dNe9n** [comment]
苹果现在换M1 ，后期可能不用intel芯片了，黑果就是最后一代了。

**Comment by konstant2016** [comment]
> 雷雳暂时没驱动，现在仅仅是个typec口 ，但是外接显示器没问题了，不过得把board-id设置为有hdmi的机型

收到，非常感谢！
