### ISSUE TITLE
大佬用的哪个版本的镜像啊

### ISSUE THREAD

**Issue by larryyssssssss** [Ac1d-0-0/MSI-GS65-9SE-hackintosh#3]
方便告知下镜像版本吗，我用的11.2.2的安装完键盘和触摸板都废了，，，，，不知道是不是镜像问题

**Comment by Ac1d-0-0** [comment]
和镜像没关系，你看看是不是一个型号的 ，这个是9SE的，其他的用不了。
一个型号的话用hackintool 定制一下usb就行

**Comment by Ac1dNe9n** [comment]
和镜像没关系，你看看是不是一个型号的 ，这个是9SE的，其他的用不了。

**Comment by Ac1dNe9n** [comment]
我现在是10.15.7catalina , big sur的话得做少量调整
