### ISSUE TITLE
请问可以分享下您的macOs版本号吗

### ISSUE THREAD

**Issue by heny** [Ac1d-0-0/MSI-GS65-9SE-hackintosh#4]

**Comment by Ac1dNe9n** [comment]
10.15.6 我现在转oc升级到bigsur了

**Comment by heny** [comment]
我下载的10.15.7卡禁止图标了，bigsur能用您这个EFI吗

**Comment by Ac1dNe9n** [comment]
你是9SE的嘛，这个只能9代u才行，然后usbport.kext删了，换成usbinjectall.kext

**Comment by Ac1dNe9n** [comment]
还有网卡我是dw1820a，你得稍微修改一下适配你自己电脑才行

**Comment by heny** [comment]
嗯，版本和您一样，2060的显卡9SE，第一次安装不太清楚，换usbinjectall.kext就是把kexts下面的USBPorts.kext直接删除掉，然后把usbinjectall.kext复制进去吗

**Comment by Ac1dNe9n** [comment]
对的，网卡你看看一样不

**Comment by Ac1dNe9n** [comment]
把-v 打开，网上查报错，稍微改改应该就能装了

**Comment by heny** [comment]
嗯，网卡不一样，我的网卡是Killer E2500，感谢大佬的指导，我再试试

**Comment by Ac1d-0-0** [comment]
AirportBrcmFixup.kext删掉 网上查intel网卡的kext，然后启动项brcmfx-country=#a brcmfx-aspm   brcmfx-driver=2都删了 
intel网卡咋驱动你得查查

**Comment by Ac1d-0-0** [comment]
高通的kext都删了就行，启动项的brcmfx-country=#a brcmfx-aspm brcmfx-driver=2也要删了，然后再查查intel网卡咋驱动就行

**Comment by Ac1dNe9n** [comment]
博通网卡的kext都删了就行，启动项的brcmfx-country=#a brcmfx-aspm brcmfx-driver=2也要删了，然后再查查intel网卡咋驱动就行

**Comment by heny** [comment]
这些删除的操作和替换的操作都是在黑苹果下面操作还是在win上操作呀

**Comment by Ac1dNe9n** [comment]
直接从文件夹删了就行 windows mac 都可

**Comment by heny** [comment]
好的，多谢大佬
